# Generated by Django 4.2.23 on 2025-07-19 06:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='deliverystatus',
            options={'verbose_name_plural': 'Delivery Status'},
        ),
        migrations.AlterField(
            model_name='notification',
            name='event_type',
            field=models.CharField(choices=[('comment', 'New Comment'), ('login', 'Unrecognized Login'), ('unrecog_login', 'Unrecognized Login'), ('summary', 'Weekly Summary')], max_length=20),
        ),
    ]
