# Generated by Django 4.2.23 on 2025-07-19 06:56

from django.db import migrations, models
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0003_rename_login_notificationpreference_unauthorized_login'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='event_type',
            field=models.CharField(choices=[('comment', 'New Comment'), ('login', 'Login'), ('unrecog_login', 'Unrecognized Login'), ('summary', 'Weekly Summary')], max_length=20),
        ),
        migrations.AlterField(
            model_name='notificationpreference',
            name='comment',
            field=multiselectfield.db.fields.MultiSelectField(choices=[('in_app', 'In-App'), ('email', 'Email'), ('sms', 'SMS')], default=['in_app', 'email', 'sms'], max_length=16),
        ),
        migrations.AlterField(
            model_name='notificationpreference',
            name='summary',
            field=multiselectfield.db.fields.MultiSelectField(choices=[('in_app', 'In-App'), ('email', 'Email'), ('sms', 'SMS')], default=['in_app', 'email', 'sms'], max_length=16),
        ),
        migrations.AlterField(
            model_name='notificationpreference',
            name='unauthorized_login',
            field=multiselectfield.db.fields.MultiSelectField(choices=[('in_app', 'In-App'), ('email', 'Email'), ('sms', 'SMS')], default=['in_app', 'email', 'sms'], max_length=16),
        ),
    ]
